string(ASCII 27 Esc)

set(Color_Black   "${Esc}[30m")
set(Color_Red     "${Esc}[31m")
set(Color_Green   "${Esc}[32m")
set(Color_Yellow  "${Esc}[33m")
set(Color_Blue    "${Esc}[34m")
set(Color_Magenta "${Esc}[35m")
set(Color_Cyan    "${Esc}[36m")
set(Color_White   "${Esc}[37m")
set(Color_Reset   "${Esc}[0m")

set(Color_Bright_Black   "${Esc}[90m")
set(Color_Bright_Red     "${Esc}[91m")
set(Color_Bright_Green   "${Esc}[92m")
set(Color_Bright_Yellow  "${Esc}[93m")
set(Color_Bright_Blue    "${Esc}[94m")
set(Color_Bright_Magenta "${Esc}[95m")
set(Color_Bright_Cyan    "${Esc}[96m")
set(Color_Bright_White   "${Esc}[97m")

set(Bg_Black   "${Esc}[40m")
set(Bg_Red     "${Esc}[41m")
set(Bg_Green   "${Esc}[42m")
set(Bg_Yellow  "${Esc}[43m")
set(Bg_Blue    "${Esc}[44m")
set(Bg_Magenta "${Esc}[45m")
set(Bg_Cyan    "${Esc}[46m")
set(Bg_White   "${Esc}[47m")

set(Bg_Bright_Black   "${Esc}[100m")
set(Bg_Bright_Red     "${Esc}[101m")
set(Bg_Bright_Green   "${Esc}[102m")
set(Bg_Bright_Yellow  "${Esc}[103m")
set(Bg_Bright_Blue    "${Esc}[104m")
set(Bg_Bright_Magenta "${Esc}[105m")
set(Bg_Bright_Cyan    "${Esc}[106m")
set(Bg_Bright_White   "${Esc}[107m")

set(Bg_Default   "${Esc}[49m")

function(print_colored_message message font_color background_color)
    if (background_color)
        message("${font_color}${background_color}${message}${Color_Reset}")
    else()
        message("${font_color}${message}${Color_Reset}")
    endif()
endfunction()

